_target_: pinnstorch.models.PINNModule
_partial_: true
loss_fn: sse
automatic_optimization: False
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  capturable: true
#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10
